name: best_flutter_ui_templates
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  scoped_model: ^1.0.1
  flutter_progress_dialog: ^0.1.0
  cache_image: ^1.0.5
  flutter_rounded_date_picker: ^1.0.4
  sliding_sheet: ^0.3.5
  dialog: ^0.7.2+1
  url_launcher: ^5.4.5

  page_transition: ^1.1.5
  route_transitions: ^1.0.2
  rflutter_alert: ^1.0.3
  provider: ^4.0.4
  flippable_box: ^1.0.6
  pinput: ^0.2.4
  shared_preferences: ^0.5.6+3
  location: ^3.0.2
  connectivity: ^0.4.8+2
  awesome_card: ^1.1.0
  scratcher: ^1.3.0
  flip_card: ^0.4.4
  share: ^0.6.4+2
  pull_to_refresh: ^1.5.8
  esys_flutter_share: ^1.0.2
  flutter_image: ^3.0.0
  #firebase
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  #google map
  flutter_map_picker: ^0.1.2
  google_maps_flutter: ^0.5.24+1
  geolocator: ^5.3.0
  http: ^0.12.0+4
  stack_trace: ^1.9.3
  package_info: ^0.4.0+14
  google_maps_webservice: ^0.0.16
  tuple: ^1.0.3
  timeago: ^2.0.26
  flutter_svg: ^0.18.0
  slide_popup_dialog: ^0.0.2
  webview_flutter: ^0.3.22+1
  google_sign_in: ^4.4.4
  progressive_image: ^1.0.1

  flutter_svg_provider: ^0.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/order/done_pro.svg
    - assets/order/done.svg
    - assets/notifi/home_loading.gif
    - assets/order/cancel.svg
    - assets/notifi/contact.png
    - assets/notifi/eqtrah.png
    - assets/config/computer.svg
    - assets/config/alert.svg
    - assets/notifi/loading_ci.gif
    - assets/fonts/WorkSans-Regular.ttf
    - assets/images/notific_active.svg
    - assets/images/notific.svg
    - assets/images/logo.png
    - assets/notifi/notifi_active.svg
    - assets/notifi/bell.svg
    - assets/images/profile_image.png
    - assets/images/feedbackImage.png
    - assets/icons-google.svg
    - assets/user.svg
    - assets/images/welcome_image/
    - assets/images/
    - assets/loading/loading_send_order.gif
    - assets/loading/loading_image.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/Cairo-SemiBold.ttf
    - family: Almarai
      fonts:
        - asset: assets/fonts/arabic/Almarai-Regular.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
